### ISSUE TITLE
Crashes on DOAJ timeout

### ISSUE THREAD

**Issue by emanuil-tolev** [DOAJ/harvester#6]

**Comment by emanuil-tolev** [comment]
```
Traceback (most recent call last):
  File "/home/cloo/harvester/src/harvester/service/runner.py", line 67, in <module>
    workflow.HarvesterWorkflow.process_account(account_id)
  File "/home/cloo/harvester/src/harvester/service/workflow.py", line 40, in process_account
    HarvesterWorkflow.process_issn(account_id, issn)
  File "/home/cloo/harvester/src/harvester/service/workflow.py", line 87, in process_issn
    saved = HarvesterWorkflow.process_article(account_id, article)
  File "/home/cloo/harvester/src/harvester/service/workflow.py", line 122, in process_article
    id, loc = doaj.create_article(article)
  File "/home/cloo/harvester/src/harvester/magnificent-octopus/octopus/modules/doaj/client.py", line 140, in create_article
    if resp.status_code == 400:
AttributeError: 'NoneType' object has no attribute 'status_code'
```

Should instead (when `resp is None`) log a message such as "Attempts at contacting DOAJ have exceeded maximum retries, stopping harvesting for now." and exit(1)
